config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # root 'goals#index'
  # root 'static_pages#root', as: 'home'
  root to: redirect('/home/index.html')

  # ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :goals do
    post 'add_milestone' => 'milestones#add_milestone'
    delete 'remove_milestone/:id' => 'milestones#remove_milestone', as: :remove_milestone
    member do
      post 'update_status(/:status)', to: 'goals#update_status', as: 'update_status'
      post 'update_motivation(/:motivation)', to: 'goals#update_motivation', as: 'update_motivation'
      patch 'update_category'
    end
    collection do
      post :filter
    end
  end

  resources :categories do
    collection do
      put 'sort', to: 'categories#sort'
    end

    member do
      post :edit, :new
    end
  end

  resources :milestones do
    member do
      post 'update_progress(/:status)', to: 'milestones#update_progress', as: 'update_progress'
      post 'achieve', to: 'milestones#achieve_milestone', as: 'achieve'
      post :edit, :new
    end

    collection do
      put 'sort_all', to: 'milestones#sort_all'
      put 'sort_in_progress', to: 'milestones#sort_in_progress'
    end
  end

  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?
end

app/models/milestone.rb
# frozen_string_literal: true

class Milestone < ApplicationRecord
  belongs_to :goal, counter_cache: true

  validates :description, presence: true

  enum :status, %i[in_progress achieved archived], default: :in_progress, prefix: true

  include RankedModel
  ranks :row_order,
        with_same: :goal_id

  ranks :in_progress_row_order,
        with_same: :goal_id,
        scope: :status_in_progress

  def update_progress(status)
    case status
    when 'achieved'
      status_achieved!
      self.update(achieved_at: DateTime.now)
    when 'in_progress'
      status_in_progress!
      goal.status_active!
    end

    goal.mark_complete
  end
end

app/controllers/milestones_controller.rb
# frozen_string_literal: true

class MilestonesController < ApplicationController
  before_action :set_milestone, only: %i[show edit update destroy
                                         update_progress achieve_milestone sort_all sort_in_progress]
  before_action :set_goal, only: %i[new edit update]

  def create
    @milestone = Milestone.new(description: create_milestone_params[:description])
    @goal = Goal.find(create_milestone_params[:goal][:goal_id])
    @goal.milestones << @milestone
    @goal.status_active! if @goal.status_achieved?
    respond_to do |format|
      if @milestone.save
        flash.now[:notice] = "Milestone #{@milestone.goal.milestones.count} is created"
        format.turbo_stream do
          render turbo_stream: [
            # in case of the milestone creation form
            # turbo_stream.append(:milestones, partial: 'milestone', locals: { milestone: @milestone }),

            # in case of the milestone creation in the goal details page
            turbo_stream.append(:inProgressMilestones, partial: 'milestone', locals: { milestone: @milestone }),
            # turbo_stream.append(:allMilestones, partial: 'milestone', locals: { milestone: @milestone }),
            turbo_stream.prepend(:flash, partial: 'partials/common/notification', locals: { style: 'green-flash' })
          ]
        end
      end
    end
  end

  def sort_all
    @milestone.update(row_order_position:
                        params[:row_order_position])
    head :no_content
  end

  def sort_in_progress
    @milestone.update(in_progress_row_order_position:
                        params[:in_progress_row_order_position])
    head :no_content
  end

  def add_milestone
    # respond_to do |format|
    #   format.turbo_stream do
    #     milestone = @goal.milestones.build
    #     render turbo_stream: [turbo_stream.append(:milestones, partial: "milestone_fields", locals: { f: milestone })]
    #   end
    # end
  end

  # def remove_milestone
  #   respond_to do |format|
  #     format.turbo_stream do
  #       milestone = @goal.milestones.find(params[:id])
  #       milestone.mark_for_destruction
  #       render turbo_stream: [turbo_stream.remove(:milestone, milestone)]
  #     end
  #   end
  # end

  # GET /milestones
  def index
    @milestones = Milestone.rank(:row_order).all
  end

  # GET /milestones/1
  def show; end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update(@milestone,
                              partial: 'milestones/form',
                              locals: { milestone: @milestone })
        ]
      end
    end
  end

  # PATCH/PUT /milestones/1
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@milestone,
                                 partial: 'milestones/milestone',
                                 locals: { milestone: @milestone }),
            turbo_stream.update('notice', 'Category is Updated')
          ]
        end
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@milestone,
                                 partial: 'milestones/form',
                                 locals: { milestone: @milestone })
          ]
        end
      end
    end
  end

  # DELETE /milestones/1
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@milestone)
        ]
      end
    end
  end

  def update_progress
    @milestone.update_progress(params[:status])
    flash.now[:notice] = 'Goal Complete!' if @milestone.goal.status_achieved?

    respond_to do |format|
      format.turbo_stream do
        case params[:status]
        when 'achieved'
          render turbo_stream: [
            turbo_stream.prepend('achievedMilestones', @milestone),
            turbo_stream.prepend(:flash,
                                 partial: 'partials/common/notification',
                                 locals: { style: 'yellow-flash',
                                           image: 'flashCup' })
          ]
        when 'in_progress'
          render turbo_stream: [
            turbo_stream.prepend('inProgressMilestones', @milestone),
            turbo_stream.replace(@milestone,
                                 partial: 'milestone',
                                 locals: { milestone: @milestone })
          ]
        end
      end
    end
  end

  def achieve_milestone
    @milestone.update_progress('achieved')
    flash.now[:notice] = 'Goal Complete!' if @milestone.goal.status_achieved?

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(@milestone.goal,
                               partial: 'goals/goal',
                               locals: { goal: @milestone.goal }),
          turbo_stream.prepend(:flash,
                               partial: 'partials/common/notification',
                               locals: { style: 'yellow-flash', image: 'flashCup' })
        ]
      end
    end
  end

  def set_milestone
    @milestone = Milestone.find(params[:id])
  end

  def set_goal
    @goal = if @milestone
              @milestone.goal
            else
              Goal.find(params[:goal_id])
            end
  end

  def milestone_params
    params.require(:milestone).permit(:description, :goal_id)
  end

  def create_milestone_params
    params.require(:milestone).permit(:description, goal: [:goal_id])
  end
end

app/helpers/milestones_helper.rb
# frozen_string_literal: true

module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_with(model: milestone, class: "flex items-end gap-x-3") do |form| %>
  <% if milestone.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>
      <ul>
        <% milestone.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.fields_for :goal do |g| %>
    <%= g.hidden_field :goal_id, value: @goal.id %>
  <% end %>
  <%= form.text_field :description,
                      class: " text-onyx block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <div class="inline">
    <%= button_tag type: 'submit',
                   class: "align-middle text-onyx" do %> &#10003
    <% end %>
    <!--    <%#= link_to :back do %> &#10007 <%# end %>-->
  </div>
<% end %>

app/views/milestones/_milestone.html.erb
<div id="<%= dom_id milestone %>" \
     class="border rounded-md bg-white p-3 flex flex-col gap-y-4"
     data-sortable-id="<%= milestone.id %>">
  <%= render(MilestoneComponent.new(milestone: milestone)) do %>
  <% end %>
</div>

app/views/milestones/_milestone_fields.html.erb
<!--<div data-target="newGoalMilestone"  class="flex gap-x-3 items-center">-->
  <%#= milestoneForm.text_field :description, class: "w-full border border-grey-200 bg-wildSand" %>
  <%#= milestoneForm.hidden_field :_destroy %>
  <%#= link_to (image_tag 'x.svg'), "#", data: { action: "click->milestones#removeMilestone" } %>
<!--</div>-->

app/views/milestones/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing milestone</h1>

  <%= render "form", milestone: @milestone %>

  <%= link_to "Show this milestone", @milestone, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to milestones", milestones_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/milestones/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-action="turbo:submit-end->dialog#submitEnd"
       class="p-5 pt-0">
    <p class="font-light text-sm text-yankeesBlue">New milestone</p>
    <%= render "form", milestone: @milestone %>
  </div>
<% end %>

app/views/milestones/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @milestone %>
  </div>
</div>