config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # root 'goals#index'
  # root 'static_pages#root', as: 'home'
  root to: redirect('/home/index.html')

  # ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :goals do
    post 'add_milestone' => 'milestones#add_milestone'
    delete 'remove_milestone/:id' => 'milestones#remove_milestone', as: :remove_milestone
    member do
      post 'update_status(/:status)', to: 'goals#update_status', as: 'update_status'
      post 'update_motivation(/:motivation)', to: 'goals#update_motivation', as: 'update_motivation'
      patch 'update_category'
    end
    collection do
      post :filter
    end
  end

  resources :categories do
    collection do
      put 'sort', to: 'categories#sort'
    end

    member do
      post :edit, :new
    end
  end

  resources :milestones do
    member do
      post 'update_progress(/:status)', to: 'milestones#update_progress', as: 'update_progress'
      post 'achieve', to: 'milestones#achieve_milestone', as: 'achieve'
      post :edit, :new
    end

    collection do
      put 'sort_all', to: 'milestones#sort_all'
      put 'sort_in_progress', to: 'milestones#sort_in_progress'
    end
  end

  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?
end

app/views/partials/common/_header.html.erb
<% if current_user %>
  <header class="flex flex-col sticky top-0 h-[7.5rem] md:h-[8.5rem] z-50 ">
    <!--    First Row-->
    <div class="
  bg-header flex h-[4rem] md:h-[5rem] justify-between items-center px-2 md:px-6 py-3">
      <%= link_to goals_path do %>
        <%= image_tag 'goalhyve.svg' %>
      <% end %>
      <%= DateTime.now.sec if Rails.env.development? %>

      <div class="flex justify-center items-center gap-x-10">
        <!--      <button data-controller="theme-switcher" data-action="click->theme-switcher#toggle" class="text-3xl font-bold bg-white rounded-3xl p-1 flex items-center justify-center gap-x-5">-->
        <!--        <span class="cursor-pointer dark:text-fiord text-philippineYellow bg-peach dark:bg-white rounded-3xl">&#9788;</span>-->
        <!--        <span class="cursor-pointer dark:text-philippineYellow text-fiord">&#x1F313;</span>-->
        <!--      </button>-->
        <div data-controller="dropdown" class="w-full flex items-center gap-x-3 justify-end">
          <div class="items-end relative flex items-center">
            <!--            Header profile image-->
            <button data-action="click->dropdown#toggle"
                    class="rounded-full w-10 h-10 md:w-14 md:h-14 bg-gray-50"></button>

            <div data-dropdown-target="dropdownContent" class="w-80 fixed right-4 top-14 md:top-20 text-fiord font-semibold z-[100] " hidden>
              <%= link_to edit_user_registration_path,
                          class: "flex items-center gap-x-4 p-5 bg-gray-50 w-full",
                          "data-action": "dropdown#select" do %>
                <%= image_tag 'settings.svg' %>
                <span> Account Settings </span>
              <% end %>

              <%= button_to destroy_user_session_path,
                            method: :delete,
                            data: { turbo: "false" },
                            class: "flex items-center gap-x-4 p-5 bg-gray-50 w-full", "data-action": "dropdown#select" do %>
                <%= image_tag 'log_out.svg' %>
                <span> Sign Out </span>
              <% end %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <!--    Second Row-->
    <div class="flex h-[3.5rem] items-center gap-x-5 md:gap-x-5 bg-gray-100 px-3 md:px-6 py-3 md:py-4 md:px-4 font-semibold text-fiord bg-gray-50 border-b border-gray-200">
      <div class="w-6">
        <% if content_for?(:toggle_side_nav_btns) %>
          <%= yield(:toggle_side_nav_btns) %>
        <% end %>
      </div>
      <%= active_link_to goals_path do %>
        <p class="hover:underline underline-offset-4 select-none"> Dashboard</p>
      <% end %>
      <%#= active_link_to '/hives', class:'' do %>
      <p class="has-tooltip select-none">
          <span class='tooltip rounded shadow-lg p-1 bg-gray-500 text-white -mt-8 text-sm font-light'> Soon.
          </span>
        Hives
      </p>
      <%# end %>
      <% if content_for?(:dropdown_filter) %>
        <%= yield(:dropdown_filter) %>
      <% end %>

    </div>

  </header>
<% end %>

app/views/partials/common/_modal.html.erb
<dialog data-dialog-target="modal"
        class="dialog"
        data-action="click->dialog#clickOutside">
  <!--    x button to close the dialog-->
  <form method="dialog" class="sticky top-0 right-0">
    <div class="flex justify-end p-3 pb-1">
      <button formmethod="dialog"
              data-action="dialog#close">
        <%= image_tag 'x.svg', class: 'bg-gray-50 rounded-full opacity-90  p-1 w-5 h-5' %>
      </button>
    </div>
  </form>
  <!--  Modal Content-->
  <%= turbo_frame_tag :modal, data: {dialog_target: 'frame'} %>

  <% if content_for?(:modal_content) %>
      <%= yield(:modal_content) %>
  <% end %>
</dialog>

app/views/partials/common/_navbar_category_container.html.erb
<div
  data-controller="toggle"
  data-action="click->categories--navbar#select"
  data-categories--navbar-target="category"
  class="w-full">
  <%= yield %>
</div>

app/views/partials/common/_notification.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= defined?(style) ? style : 'green-flash'  %>"
       data-controller="autohide">
    <% if defined?image %>
      <%= image_tag "flash/#{image}.svg" %>
    <% end %>
    <%= value %>
  </div>
<% end %>

app/views/partials/common/_page_header.html.erb
<div class="flex justify-between items-center border-b border-gray-200 pr-6 py-5 sticky top-[0] right-0 w-full bg-gray-50 z-10">
  <div class="hidden md:block text-2xl font-semibold text-yankeesBlue pl-6">
    <%= page_name %>
  </div>
</div>

app/views/partials/common/_side_nav.html.erb
<!--<div class="hidden w-1/12  px-1 py-7 md:px-4 md:py-7 lg:p-7 bg-gray-50 border-r border-gray-200 flex justify-center">-->
<!--  <button class="bg-zircon rounded-full md:p-2 h-fit" data-action="toggle#spread">-->
<%#= image_tag 'spread.svg', class: 'h-5 h-5' %>
<!--  </button>-->
<!--</div>-->
<!--Side navigation bar-->
<div class="hidden lg:block w-2/12 h-[inherit] bg-gray-50 z-50 lg:z-auto"
     data-toggle-side-nav-target="sideNav"
     data-action="click->dialog#clickOutside">
  <div class=" bg-gray-50
flex flex-col gap-y-4 py-6 px-4  justify-start items-center fixed w-[inherit] h-[inherit] border-r border-gray-200"
       data-controller="categories--navbar">
    <!--  Create a Goal-->
      <%= link_to new_goal_path,
                  data: { turbo_frame: "modal" },
                  class: "h-fit w-full rounded-3xl py-1.5 text-center bg-ceruleanBlue text-white block font-semibold flex justify-center items center gap-x-3",
                  "data-action": "click->toggle-side-nav#hideSideNav dialog#open" do %>
    <%= image_tag 'plus.svg' %>
      <span>Create a goal</span>
    <% end %>
    <!--  Categories Section-->
    <div class="flex flex-col h-[inherit] flex-grow  w-full border border-solid dark:border-none border-gray-300 rounded-lg  bg-lotion dark:bg-dark-navbarInsider overflow-y-auto"
         data-controller="form"
    >
      <!--  Create a new Category-->
      <div class="flex justify-between items-center bg-white w-full rounded-t-xl p-2 dark:bg-dark-navbar">
        <p class="font-semibold text-yankeesBlue ">Categories</p>
        <%= button_to new_category_path(@milestone),
                      method: :post,
                      data:{action: 'form#scrollToTop'},
                      class: "border border-solid border-gray-200 flex justify-center items-center h-7 w-7 p-2 bg-zircon rounded-3xl text-2xl text-doveGray" do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M8 1V15M1 8H15" stroke="#415472" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        <% end %>
      </div>
      <!--    Categories-->
      <%= render partial: 'categories/index' %>
    </div>
    <!--  Account Settings, Sign Out, Logo-->
    <div class="flex flex-col justify-start items-start gap-y-2  w-full text-independence font-semibold self-end ">
      <p class="font-black mt-6">GoalHyve.Inc ™</p>
    </div>
  </div>
</div>

app/views/partials/common/_sign_container.html.erb
<div class="text-black w-full h-screen flex justify-center items-center bg-floralWhite ">
  <div class="w-fit flex justify-center relative">
    <%= image_tag 'orangeblur.png', class: "absolute top-0  right-0 w-52 h-auto object-contain z-10" %>
    <%= image_tag 'purpleblur.png', class: "absolute bottom-0 left-0  w-52 h-auto object-contain z-10" %>
    <div class="w-full p-5 md:p-20">
      <div class="bg-white border-2 border-solid border-gray-100 max-w-md w-fit p-8 rounded-xl flex flex-col gap-y-3 items-center relative z-20">
        <div class="w-full text-center p-4 rounded-lg"
             style="background: linear-gradient(82deg, #3A00FF -19.94%, #9773FE 31.65%, #F4E7FD 100.99%);
               background-size: 100% auto; background-position: center;">
          <%= image_tag 'welcoming-hive.jpg',
                        alt: "Group of welcoming people",
                        class: "mt-[-32px] pt-6 lg:w-max max-w-full h-auto object-contain mx-auto" %>
        </div>
        <div class="w-full flex flex-col gap-y-3 w-full">
          <div class="w-full  text-center">
            <h2 class="w-full  text-xl md:text-2xl font-bold p-2 text-yankeesBlue">Welcome to
              Goal<span class="text-ceruleanBlue">Hyve</span></h2>
          </div>
          <!--  Sign in/up content-->
          <%= yield %>
          <%= render "devise/shared/links" %>
        </div>
      </div>
    </div>
  </div>
</div>