config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # root 'goals#index'
  # root 'static_pages#root', as: 'home'
  root to: redirect('/home/index.html')

  # ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :goals do
    post 'add_milestone' => 'milestones#add_milestone'
    delete 'remove_milestone/:id' => 'milestones#remove_milestone', as: :remove_milestone
    member do
      post 'update_status(/:status)', to: 'goals#update_status', as: 'update_status'
      post 'update_motivation(/:motivation)', to: 'goals#update_motivation', as: 'update_motivation'
      patch 'update_category'
    end
    collection do
      post :filter
    end
  end

  resources :categories do
    collection do
      put 'sort', to: 'categories#sort'
    end

    member do
      post :edit, :new
    end
  end

  resources :milestones do
    member do
      post 'update_progress(/:status)', to: 'milestones#update_progress', as: 'update_progress'
      post 'achieve', to: 'milestones#achieve_milestone', as: 'achieve'
      post :edit, :new
    end

    collection do
      put 'sort_all', to: 'milestones#sort_all'
      put 'sort_in_progress', to: 'milestones#sort_in_progress'
    end
  end

  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?
end

app/models/goal.rb
# frozen_string_literal: true

class Goal < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :milestones,
           class_name: 'Milestone',
           dependent: :destroy,
           counter_cache: :milestones_count

  accepts_nested_attributes_for :milestones, :category

  has_one_attached :motivation_media

  validates :description, presence: true
  validates :milestones, presence: { message: 'must have at least one milestone' }, on: :create

  scope :by_category, ->(category) { where(category: category) }
  scope :by_status, ->(status) { where(status: status) }

  scope :by_category_and_status, lambda { |status, category|
    scope = if status.present?
              by_status(status)
            else
              by_status('active')
            end
    scope = scope.by_category(category) if category.present?
    scope
  }

  enum :status, %i[paused active achieved archived], default: :active, prefix: true

  def toggle_status
    if status_paused?
      status_active!
    else
      status_paused!
    end
  end

  def mark_complete
    status_achieved! if milestones.status_in_progress.empty?
  end

  def achieved_count
    milestones.where(status: 'achieved').count
  end

  def goal_progress_percentage
    milestones_count != 0 ? (achieved_count * 100) / milestones_count : 0
  end
end

app/controllers/goals_controller.rb
# frozen_string_literal: true

class GoalsController < ApplicationController
  before_action :set_goal, only: %i[show edit update destroy update_status update_motivation update_category]
  before_action :set_ordered_milestones, only: %i[show]
  before_action :set_goals, only: %i[index]
  before_action :set_current_filters, only: %i[create filter index]
  before_action :filter_params, only: %i[filter]

  # GET /goals or /goals.json
  def index
    @goals = @goals.status_active
  end

  def filter
    category = filter_params[:category]
    status = filter_params[:status]
    @goals = current_user.goals.order(created_at: :desc).by_category_and_status(status, category)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('goals',
                               partial: 'goals/list',
                               locals: { goals: @goals })
        ]
      end
    end
  end

  # GET /goals/1 or /goals/1.json
  def show; end

  # GET /goals/new
  def new
    @goal = Goal.new
    @goal.milestones.build
    @goal.build_category
  end

  # GET /goals/1/edit
  def edit; end

  # POST /goals or /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.category = find_or_create_category[:category]
    new_category = find_or_create_category[:new_category]
    @goal.user = current_user
    respond_to do |format|
      if @goal.save
        flash.now[:notice] = 'Goal is created'
        format.turbo_stream do
          actions = []
          # if it is all category or same category and 'active status'
          if (@current_category == 'all' || @current_category.to_i == @goal.category_id) && @current_status == 'active'
            actions << turbo_stream.prepend('goals', partial: 'goals/goal',
                                            locals: { goal: @goal })
          end
          if new_category
            actions << turbo_stream.append('categories', partial: 'categories/category',
                                           locals: { category: @goal.category })
          end
          actions << turbo_stream.prepend(:flash,
                                          partial: 'partials/common/notification',
                                          locals: { style: 'green-flash' })

          render turbo_stream: actions
        end
        # format.html { redirect_to goal_url(@goal), notice: 'Goal was successfully created.' }
        # format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1 or /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        flash.now[:notice] = 'Goal was successfully updated.'
        format.turbo_stream do
          actions = []
          actions << turbo_stream.prepend(:flash,
                                          partial: 'partials/common/notification',
                                          locals: { style: 'green-flash' })
          # if params[:goal][:motivation_media]
          #   actions << turbo_stream.replace('motivationMedia',
          #                                   partial: 'details/motivation_media',
          #                                   locals: { goal: @goal })
          # end
          render turbo_stream: actions
        end
        format.html { redirect_to goal_url(@goal), notice: 'Goal is updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1 or /goals/1.json
  def destroy
    @goal.destroy
    flash.now[:notice] = 'Goal Deleted'

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@goal),
          turbo_stream.prepend(:flash,
                               partial: 'partials/common/notification',
                               locals: { style: 'red-flash', image: 'flashRemove' })
        ]
      end
    end
  end

  def update_motivation_media
    flash.now[:notice] = "Motivation media has been updated"
  end

  def update_status
    @goal.toggle_status
    flash.now[:notice] = "Goal #{@goal.status.capitalize}"
    image = @goal.status_paused? ? 'flashPause' : 'flashResume'

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@goal),
          turbo_stream.prepend(:flash,
                               partial: 'partials/common/notification',
                               locals: { style: 'blue-flash', image: })
        ]
      end
    end
  end

  def update_motivation
    @goal.update(motivation: params[:motivation].strip)
    flash.now[:notice] = 'Motivation has been updated'
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.prepend(:flash,
                               partial: 'partials/common/notification',
                               locals: { style: 'blue-flash' })
        ]
      end
    end
  end

  def update_category
    respond_to do |format|
      if @goal.update(category: find_or_create_category[:category])
        flash.now[:notice] = "Goal has been moved to: #{@goal.category.name.capitalize}"
        format.turbo_stream do
          render turbo_stream:
                   turbo_stream.prepend(:flash,
                                        partial: 'partials/common/notification',
                                        locals: { style: 'blue-flash' })
        end
        format.html { redirect_to goal_url(@goal), notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_ordered_milestones
    @ordered_milestones = @goal.milestones.order(updated_at: :desc)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_goal
    @goal = Goal.find(params[:id])
  end

  def set_goals
    @goals = current_user.goals.order(created_at: :desc).includes([:category])
  end

  def find_or_create_category
    new_category = false
    category = nil
    if goal_params.dig(:category_attributes, :name).present?
      new_category = true
      category = current_user.categories.build(name: goal_params[:category_attributes][:name])
    elsif goal_params[:category_id].present?
      category = Category.find(goal_params[:category_id])
    end
    { category:, new_category: }
  end

  # Only allow a list of trusted parameters through.
  def goal_params
    params.require(:goal).permit(:description,
                                 :motivation,
                                 :category_id,
                                 :begin_date,
                                 :end_date,
                                 :motivation_media,
                                 milestones_attributes: %i[id description _destroy],
                                 category_attributes: %i[name])
  end

  def filter_params
    params.require(:by_category_and_status).permit(:category, :status)
  end

  def set_current_filters
    case action_name
    when 'filter'
      session[:current_category] = filter_params[:category]
      session[:current_status] = filter_params[:status]
    when 'index'
      session[:current_category] = 'all'
      session[:current_status] = 'active'
    else
      @current_category = session[:current_category].empty? ? 'all' : session[:current_category]
      @current_status = session[:current_status].empty? ? 'active' : session[:current_status]
    end
  end
end

app/helpers/goals_helper.rb
# frozen_string_literal: true

module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal,
              url: goals_path,
              class: 'w-full h-full',
              data: { controller: 'new-goal-milestones stepper',
                      action: 'new-goal-milestones#filterEmptyMilestones
                               new-goal-milestones:removeMilestone@window->stepper#enableNext' }) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex h-full flex-col gap-y-3 justify-between">
    <!--    ٍStep Number-->
    <div class="bg-wildSand flex items-center gap-x-3 w-fit p-3 text-fiord  font-medium rounded-md">
      <%= image_tag 'stars.svg' %>
      <p> Step
        <span data-stepper-target="stepNumber"> - </span> of
        <span data-stepper-target="numberOfSteps"> - </span></p>
    </div>
    <!--    Content (Steps)-->
    <div class="flex-1 overflow-auto  font-medium text-fiord text-lg">
      <!--      Step 1: Goal, Motivation Category  -->
        <%= render 'partials/new_goal_stepper/step_1_goal_details', form: form %>
      <!--      Step 2: Developing Milestones step -->
         <%= render 'partials/new_goal_stepper/step_2_create_milestones', form: form %>
      <!--      Step 3: Choosing Category step -->
        <%= render 'partials/new_goal_stepper/step_3_choose_category', form: form %>
      <!--      Step 4: Assign Begin date, End date-->
        <%= render 'partials/new_goal_stepper/step_4_choose_dates', form: form %>
    </div>
    <!--    Navigation Buttons-->
    <div class="self-end flex justify-end gap-x-4 font-medium">
      <button class="bg-zircon rounded-3xl px-4 py-2 text-independence"
              data-action="stepper#previous"
              data-stepper-target="prev">
        ← Back
      </button>
      <button class="bg-ceruleanBlue rounded-3xl px-4 py-2 text-white
                     disabled:bg-wildSand
                     disabled:cursor-not-allowed
                     disabled:text-doveGray
                     disabled:has-tooltip
                     disabled:cursor-help"
              data-action="stepper#next"
              data-stepper-target="next"
              disabled="true">
        <span class='tooltip rounded shadow-lg p-1 bg-gray-500 text-white bottom-24 -ml-[10%] text-sm font-light'
              data-stepper-target="nextTooltip">
        </span>
        Next →
      </button>
      <div class="bg-ceruleanBlue w-fit flex justify-center items-center rounded-3xl px-5 py-1 text-white inline-block cursor-pointer hidden"
           data-stepper-target="submit">
        <%= form.submit 'Create Goal', class: "cursor-pointer" %>
      </div>
    </div>
  </div>
<% end %>

app/views/goals/_goal.html.erb
<%= render(GoalCardComponent.new(goal: goal)) do %>
<% end %>

app/views/goals/_list.html.erb
<div  id="goals"
      class="p-6 scroll-smooth w-full grid justify-items-center grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-7 md:gap-10 ">
  <%= render @goals || goals %>
</div>

app/views/goals/_update_category.html.erb
<p class="text-xl font-bold text-yankeesBlue">Choose a category to move your goal to</p>
<p class="text-doveGray text-base">Current Category : <%= @goal.category.name %></p>
<div data-action="turbo:submit-end->dialog#submitEnd">
  <%= form_with(model: @goal, url: update_category_goal_path(@goal), method: :patch) do |form| %>
    <% content_for :confirm_update do %>
      <%= form.submit 'Update',
                      class: 'cursor-pointer hover:bg-indigo-50 p-2 rounded-lg' %>
    <% end %>
    <%= render 'categories/controller', form: form %>
</div>

<% end %>

app/views/goals/dropdown_filter.html.erb
<div data-controller="dropdown" class="flex items-center gap-x-3 ml-auto">
  <label for="status" class="hidden md:block text-sm font-medium text-quickSilver whitespace-nowrap">Goal Status</label>
  <div class="inline-block items-end relative w-36 md:w-40">
    <button data-action="click->dropdown#toggle" class="h-full flex justify-between items-center gap-x-1 bg-indigo-50 rounded-full w-full">
      <span data-dropdown-target="selectedText" class="px-5 w-7/12 flex justify-start  text-fiord font-semibold">Active</span>
      <div class="bg-indigo-100  rounded-r-full p-4  ">
        <%= image_tag 'arrow_down.svg' %>
      </div>
    </button>

    <div data-dropdown-target="dropdownContent" class="w-40 absolute right-0 top-11 md:top-12 bg-indigo-50 text-fiord font-semibold" hidden>
      <% { active: "Active", paused: "Paused", achieved: "Achieved" }.each do |key, value| %>
        <button data-option-text="<%= value %>"
                data-option-value="<%= key %>"
                class="bg-indigo-50 py-3 px-3 w-full flex justify-start hover:font-semibold hover:bg-indigo-100"
                data-action="dropdown#select goals-filter#filterByStatus">
          <%= value %>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing goal</h1>

  <%= render "form", goal: @goal %>

  <%= link_to "Show this goal", @goal, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to goals", goals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/goals/index.html.erb
<% content_for :side_nav do %>
  <%= render 'partials/common/side_nav' %>
<% end %>

<% content_for :dropdown_filter do %>
  <%= render template: 'goals/dropdown_filter' %>
<% end %>

<% content_for :toggle_side_nav_btns do %>
  <!--  Fold Button-->
  <button class="block lg:hidden w-5 justify-center items-center"
          data-toggle-side-nav-target="unfoldBtn"
          data-action="toggle-side-nav#toggle">
    <%= image_tag 'toggle.svg', class: 'h-4 w-4 md:h-4 md:h-4' %>
  </button>
  <!--  Unfold Button-->
  <button class="hidden lg:block w-5 flex justify-center items-center"
          data-toggle-side-nav-target="foldBtn"
          data-action="toggle-side-nav#toggle">
    <%= image_tag 'collapse.svg', class: 'h-4 w-4 md:h-5 md:h-5' %>
  </button>
<% end %>

<% content_for :goals_list do %>
  <section class="flex flex-col flex-grow w-8/12 md:w-9/12 lg:w-10/12 bg-gray-50 h-fit"
           data-toggle-side-nav-target="hidden">
    <!--  header-->
    <%#= render partial: 'partials/common/page_header', locals: { page_name: 'Dashboard' } %>
    <!--  Body-->
    <%= render partial: 'goals/list', goals: @goals || goals %>
  </section>
<% end %>

app/views/goals/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-action="turbo:submit-end->dialog#submitEnd"
       class="relative p-5 w-90v h-90v md:w-70v md:h-80v lg:w-60v ">
      <%= render "form", goal: @goal %>
  </div>
<% end %>

app/views/goals/show.html.erb
<% content_for :goal_details do %>
  <div class='flex justify-around gap-x-16 items-start p-2 md:p-5'>
    <!--  1st section-->
    <div class='w-3/12 hidden lg:flex flex-col gap-y-5 sticky top-5'>
      <%= render 'details/motivation_text' %>
      <%= render 'details/motivation_media' %>
    </div>
    <!--  2nd section-->
    <div class="w-full lg:w-6/12 flex flex-col"
         data-controller="edit-content">
      <!--      Motivation & Activity for mobile-->
      <div class="flex justify-between gap-x-5">
        <p class="text-2xl truncate text-yankeesBlue font-semibold w-full p-2"
           data-edit-content-target="content">
          <%= @goal.description %>
        </p>
        <div class="flex  gap-x-3">
<!--          Edit Button-->
          <button class='flex justify-center items-center'
                  data-action='edit-content#editMode'
                  data-edit-content-target="editBtn">
            <%= image_tag 'edit.svg' %>
          </button>
<!--          Check Button-->
          <button class='hidden flex justify-center items-center text-ceruleanBlue bold text-lg'
                  data-action='edit-content#saveMode'
                  data-update-url='<%= goals_path %>'
                  data-goal-id='<%= @goal.id %>'
                  data-edit-content-target="updateBtn">
            <%= image_tag 'check.svg', class: 'w-4 h-4' %>
          </button>
<!--          Update Category Button-->
          <button class='flex justify-center items-center'
                  data-action='dialog#open'
                  data-dialog-content-id="update_category">
            <%= image_tag 'folder.svg' %>
            <% content_for :modal_content do %>
              <div class="w-60v p-8 flex flex-col gap-y-3"
                   id='update_category'
                   data-dialog-target="content">
                <%= render 'goals/update_category' %>
              </div>
            <% end %>
          </button>
        </div>
      </div>
<!--      Tabs Section-->
      <div
        data-controller="tabs"
        data-tabs-active-class="border border-gray-400 rounded-3xl bg-white text-independence"
        data-tabs-default-tab-value="inProgressMilestones"
      >
        <!-- buttons to toggle between tabs -->
        <div class="flex justify-between items-center sticky top-0 py-2 bg-gray-50">
          <!--          Buttons-->
          <div class="text-doveGray list-reset flex gap-x-3 justify-center items-center border rounded-3xl p-1 w-fit bg-slate-50 ">
            <button data-tab-id="inProgressMilestones" data-tabs-target="btn defaultBtn" data-action="click->tabs#select" class="milestone_tab">In-progress
              <span class="hidden md:inline">Milestones</span>
            </button>
            <button data-tab-id="achievedMilestones" data-tabs-target="btn" data-action="click->tabs#select" class="milestone_tab">Achieved
              <span class="hidden md:inline">Milestones</span>
            </button>
            <!--            <button data-tab-id="allMilestones" data-tabs-target="btn" data-action="click->tabs#select" class="milestone_tab"> -->
            <!--             All Milestones-->
            <!--            </button>-->
          </div>
          <!--          Add a new Milestone, Motivation, Activity-->
          <div class="flex justify-center items-center gap-x-4">
            <button class='lg:hidden flex justify-between items-center p-2 rounded-full bg-[#F4F6FF]'
                    data-action='dialog#open'
                    data-dialog-content-id="motivation">
              <%= image_tag 'motivation.svg' %>
              <% content_for :modal_content do %>
                <div class="w-90v h-90v p-3 flex flex-col gap-y-3"
                     id='motivation'
                     data-dialog-target="content">
                  <%= render 'details/motivation_text' %>
                  <%= render 'details/motivation_media' %>
                </div>
              <% end %>
            </button>

            <button class='lg:hidden flex justify-between items-center p-2 rounded-full bg-[#F4F6FF]'
                    data-action='dialog#open'
                    data-dialog-content-id="activity">
              <%= image_tag 'activity.svg' %>
              <% content_for :modal_content do %>
                <div class="w-90v h-90v p-3"
                     id='activity'
                     data-dialog-target="content">
                  <%= render 'details/recent_activity', goal: @goal %>
                </div>
              <% end %>
            </button>

            <%= button_to new_milestone_path(goal_id: @goal.id),
                          method: :post,
                          class: 'gap-x-2 bg-ceruleanBlue flex justify-between items-center p-2 md:py-1 md:px-4 rounded-full  md:rounded-3xl',
                          data: { turbo_frame: "modal",
                                  action: 'dialog#open' } do %>
              <%= image_tag 'plus.svg' %>
              <span class="hidden md:block font-semibold text-md text-white"> Add Milestone </span>
            <% end %>
          </div>
        </div>
        <!-- the tabs -->
        <div class="rounded-lg">
          <div data-tabs-target="tab defaultTab"
               id="inProgressMilestones"
               class="hidden milestone_tab_content"
               data-controller="sortable"
               data-sortable-url="<%= sort_in_progress_milestones_path %>"
               data-sortable-list="in-progress"
               data-sortable-position="in_progress_row_order_position">
            <%= render @goal.milestones.where(status: 'in_progress').rank(:in_progress_row_order).all %>
          </div>

          <div data-tabs-target="tab" id="achievedMilestones" class='hidden milestone_tab_content'>
            <%= render @goal.milestones.where(status: 'achieved') %>
          </div>

          <div data-tabs-target="tab"
               id="allMilestones"
               class='hidden milestone_tab_content'
               data-controller="sortable"
               data-sortable-url="<%= sort_all_milestones_path %>"
               data-sortable-position="row_order_position">
            <%= render @goal.milestones.rank(:row_order).all %>
          </div>
        </div>
      </div>
    </div>
    <!--  3rd section-->
    <div class="w-3/12 hidden lg:block sticky top-5">
      <%= render 'details/recent_activity', goal: @goal %>
    </div>
  </div>

<% end %>