config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # root 'goals#index'
  # root 'static_pages#root', as: 'home'
  root to: redirect('/home/index.html')

  # ,controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :goals do
    post 'add_milestone' => 'milestones#add_milestone'
    delete 'remove_milestone/:id' => 'milestones#remove_milestone', as: :remove_milestone
    member do
      post 'update_status(/:status)', to: 'goals#update_status', as: 'update_status'
      post 'update_motivation(/:motivation)', to: 'goals#update_motivation', as: 'update_motivation'
      patch 'update_category'
    end
    collection do
      post :filter
    end
  end

  resources :categories do
    collection do
      put 'sort', to: 'categories#sort'
    end

    member do
      post :edit, :new
    end
  end

  resources :milestones do
    member do
      post 'update_progress(/:status)', to: 'milestones#update_progress', as: 'update_progress'
      post 'achieve', to: 'milestones#achieve_milestone', as: 'achieve'
      post :edit, :new
    end

    collection do
      put 'sort_all', to: 'milestones#sort_all'
      put 'sort_in_progress', to: 'milestones#sort_in_progress'
    end
  end

  mount Lookbook::Engine, at: '/lookbook' if Rails.env.development?
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :goals, dependent: :destroy
  belongs_to :user
  validates :name, presence: true

  include RankedModel
  ranks :row_order,
        with_same: :user_id
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy sort]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  def sort
    @category.update(row_order_position:
                       params[:row_order_position])
    head :no_content
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.prepend('categories',
                               partial: 'categories/form',
                               locals: { category: @category })
        ]
      end
    end
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        flash.now[:notice] = "Category #{@category.name} is created"
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.append('categories',
                                partial: 'categories/category',
                                locals: { category: @category }),
            turbo_stream.remove('new_category'),
            turbo_stream.prepend(:flash,
                                 partial: 'partials/common/notification',
                                 locals: { style: 'green-flash' })
          ]
        end
        #   format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        #   format.json { render :show, status: :created, location: @category }
        # else
        #   format.html { render :new, status: :unprocessable_entity }
        #   format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # post /categories/1/edit
  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace(@category,
                               partial: 'categories/form',
                               locals: { category: @category })
        ]
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@category,
                                 partial: 'categories/category',
                                 locals: { category: @category,
                                           selected: params[:selected].to_boolean }),
            turbo_stream.update('notice', 'Category is Updated')
          ]
        end
        # format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        # format.json { render :show, status: :ok, location: @category }
      else
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.replace(@category,
                                 partial: 'categories/form',
                                 locals: { category: @category })
          ]
        end
        # format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.remove(@category),
          turbo_stream.update('notice', 'Category is removed'),
          turbo_stream.replace('goals',
                               partial: 'goals/list',
                               locals: { goals: current_user.goals.status_active.all })
        ]
      end
      # format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      # format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_category.html.erb
<div
  id="<%= dom_id category %>"
  data-controller="toggle"
  data-action="click->categories--navbar#select
               click->goals-filter#filterByCategory"
  data-category-id=<%= category.id %>
  data-sortable-id=<%= category.id %>
  data-categories--navbar-target="category"
  class="navbar_category navbar_category_hover w-full flex justify-between items-center gap-x-2
        <%= action_name == 'update' && selected ? 'selected_category' : '' %>">
  <div class="flex justify-start items-center w-full cursor-pointer truncate py-4 px-2 ">
    <%= category.name %>
  </div>


  <div class="flex justify-end items-center gap-x-2  px-2 h-full">
    <!--      Delete, Category, Details-->
    <div class="hidden flex justify-end items-center gap-x-2" data-toggle-target="toggledContent" data-category-element="options">
      <div data-action="turbo:submit-end->categories--navbar#deleteCategorySubmitEnd">
        <%= button_to (image_tag 'delete.svg'),
                      category_path(category),
                      method: :delete,
                      form: { data: { turbo_confirm: 'Are you sure you want to delete this category?' } },
                      class: "w-8 h-8 flex justify-center items-center rounded-2xl py-2 px-2 bg-red-100" %>
      </div>
      <%= button_to (image_tag 'edit.svg'),
                    edit_category_path(category),
                    method: :post,
                    class: "w-8 h-8 flex justify-center items-center rounded-2xl py-2 px-2 bg-gray-100 inline-block font-medium" %>
      <!--      Toggle category menu btn-->
      <button data-action="click->toggle#toggleContent"
              class="flex justify-center items-center rounded-2xl bg-zircon w-8 h-8 text-xl text-independence p-2 font-medium">
        <span>&#10007;</span>
      </button>
    </div>
    <button data-action="click->toggle#toggleContent"
            data-toggle-target="toggleBtn"
            data-category-element="btn"
            class="<%= action_name == 'update' && selected ? '' : 'hidden' %> h-full my-handle">
      <%= image_tag 'dots.svg' %>
    </button>
  </div>
</div>

app/views/categories/_category_form.html.erb
<div class="flex gap-x-5 flex-wrap gap-y-3 pb-4 w-full">
  <% current_user.categories.each do |category| %>
    <div class="max-w-2xl">
      <%= form.radio_button :category_id,
                            category.id,
                            'data-stepper-target': "newGoalCategoryOption",
                            'data-action': 'stepper#enableNext
                                            stepper#resetNewCategoryInput
                                            categories#resetNewCategoryInput
                                            toggle#hideContent',
                            class: "sr-only peer" %>
      <label class="category_form_label"
             for="goal_category_id_<%= category.id %>">
        <%= category.name %>
      </label>
    </div>
  <% end %>
</div>

app/views/categories/_controller.html.erb
<div class="flex flex-col gap-y-3 pb-4 w-full"
     data-controller="toggle categories">
    <%= render 'categories/category_form', form: %>
  <div class="flex gap-x-3 justify-between ">
    <%= render 'categories/new_category_form', form: %>
    <% if content_for?(:confirm_update) %>
      <%= yield(:confirm_update) %>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<div id="<%= dom_id category %>"
     data-sortable-id=<%= category.id %>>
  <%= form_with(model: category,
                class: "contents") do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= hidden_field_tag :selected, true %>

    <div class="flex gap-x-3 text-lgx">
      <%= form.text_field :name,
                          class: "shadow rounded-md  outline-none w-full text-independence font-semibold",
                          placeholder: "New Category",
                          autofocus: true  %>
      <div class="text-independence  ">
        <%= form.submit '✓',
                        id: 'submit_category',
                        class: "cursor-pointer rounded-full align-middle bg-gray-100 w-full" %>
        <button class="rounded-full align-middle bg-gray-100 w-full">
          ✗
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/_index.html.erb
<% if current_user %>
  <!--      Categories-->
  <div class="scroll-smooth overflow-auto w-full px-2 py-3 flex flex-col justify-start items-center pb-2 h-[inherit] gap-y-1"
       data-form-target='scrollableParent'>
    <div
      id='default_category'
      data-controller="toggle"
      data-action="click->categories--navbar#select
                   click->goals-filter#filterByCategory
                   click->toggle-side-nav#hideSideNav"
      data-categories--navbar-target="default"
      class="navbar_category navbar_category_hover py-3 px-2 w-full">
      <button class="w-full flex justify-start items-center truncate">All Categories</button>
    </div>
    <div id="categories"
         class="w-full flex flex-col gap-y-1"
         data-controller="sortable"
         data-sortable-url="<%= sort_categories_path %>"
         data-sortable-position="row_order_position">
      <%= render current_user.categories.rank(:row_order).all %>
    </div>
  </div>
<% end %>

app/views/categories/_new_category_form.html.erb
<div class="hidden flex justify-start items-center gap-x-3 w-full"
     data-toggle-target="toggledContent">
  <%= form.fields_for :category_attributes do |category_fields| %>
    <div class="flex gap-x-3 w-full">
      <%= category_fields.text_field :name,
                                     class: "goal_input text-doveGray shadow rounded-md outline-none font-base",
                                     placeholder: "Your new category name!",
                                     value: '',
                                     'data-stepper-target': 'newCategoryInput',
                                     'data-categories-target': 'newCategoryInput',
                                     'data-action': 'keydown.enter->stepper#FocusOnNextTarget
                                                                      stepper#enableNext' %>
    </div>
  <% end %>
</div>

<button
  data-stepper-target="newGoalCategoryBtn"
  data-action="toggle#toggleContent
                 stepper#unselectCategoriesOptions
                 stepper#disableNext
                 stepper#FocusOnNextTarget"
  data-toggle-target="toggleBtn"
  class="text-ceruleanBlue flex justify-start w-fit rounded-md">
  <p>Create New Category?</p>
</button>

app/views/categories/_new_goal_category.html.erb
<div class="max-w-2xl">
  <%= form.radio_button :category_id,
                        category.id,
                        'data-stepper-target': "newGoalCategoryOption",
                        class: "sr-only peer" %>
  <label class="flex px-3 py-1 bg-zircon  text-fiord rounded-md border border-gray-300 cursor-pointer focus:outline-none hover:bg-gray-50
              peer-checked:ring-green-500
              peer-checked:ring-2
              peer-checked:border-transparent
              truncate" for="goal_category_id_<%= category.id %>">
    <%= category.name %></label>
</div>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%#= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/new.html.erb
<%#= turbo_frame_tag :modal do %>
<!--  <div data-controller="turbo-modal" data-action="turbo:submit-end->turbo-modal#submitEnd">-->
<!--    <div id="new_category">-->
<!--      <div class="mx-auto md:w-2/3 w-full">-->
<!--        <p class="font-bold">New category</p>-->

        <%#= render "form", category: @category %>
<!--        <button data-action="click->turbo-modal#hideModal"> close </button>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<%# end %>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%#= link_to 'Edit this category', edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<!--    <div class="inline-block ml-2">-->
      <%#= button_to 'Destroy this category', category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
<!--    </div>-->
    <%#= link_to 'Back to categories', categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>